server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: admin
  data:
    mongodb:
      uri: mongodb://localhost:27017/TraceabilityDB
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  urls:
    urlToUserMicroService: "http://localhost:8090/"
    urlToMessagingMicroService: "http://localhost:8092/"